function [EnumeratorParams,name] = getEnumeratorBoutKinematicParams()
str = {'numbHalfBeats','boutDuration','maxbeatFreq','minbeatFreq','meanbeatFreq','maxTailChangeAvr','meanTailChangeAvr',...
    'maxTailChangeMax','meanTailChangeMax','maxboutTailWaveSpeedAll','minboutTailWaveSpeedAll','meanboutTailWaveSpeedAll',...
    'maxboutTailAngularVelocityAll','minboutTailAngularVelocityAll','meanboutTailAngularVelocityAll','maxboutTailAmplitudePositionRateAll',...
    'minboutTailAmplitudePositionRateAll','meanboutTailAmplitudePositionRateAll','maxboutHalfBendingPosAll','minboutHalfBendingPosAll','meanboutHalfBendingPosAll',...
    'maxboutCruvatureAll','minboutCruvatureAll','meanboutCruvatureAll','maxboutCurvatureRateAll','minboutCurvatureRateAll','meanboutCurvatureRateAll',...
    'boutAbsAmplitude1Avr','boutAbsAmplitude2Avr','boutAbsAmplitude3Avr','boutAbsAmplitude4Avr','boutAbsAmplitude5Avr','boutAbsAmplitude6Avr','boutAbsAmplitude7Avr',...
    'boutAbsAmplitude8Avr','boutAbsAmplitude9Avr','boutAbsAmplitude10Avr','boutAmplitude1Max','boutAmplitude2Max','boutAmplitude3Max','boutAmplitude4Max',...
    'boutAmplitude5Max','boutAmplitude6Max','boutAmplitude7Max','boutAmplitude8Max','boutAmplitude9Max','boutAmplitude10Max',...
    'hb1_ud','hb1_numBeat','hb1_dur','hb1_freq','hb1_amp1','hb1_amp2','hb1_amp3','hb1_amp4','hb1_amp5','hb1_amp6','hb1_amp7','hb1_amp8','hb1_amp9','hb1_amp10',...
    'hb1_ampAvr','hb1_ampMax','hb1_maxTailAngle','hb1_minTailAngle','hb1_halfBendAngle','hb1_maxTailPos','hb1_minTailPos','hb1_halfBendPos','hb1_waveSpeed',...
    'hb1_angularVel','hb1_ampPosRate','hb1_auc1','hb1_auc2','hb1_auc3','hb1_auc4','hb1_auc5','hb1_auc6','hb1_auc7','hb1_auc8','hb1_auc9','hb1_auc10','hb1_aucAvr',...
    'hb1_aucMax','hb1_maxTailChange','hb1_meanTailChange','hb1_maxCurv','hb1_maxCurvRate',...
    'hb2_ud','hb2_numBeat','hb2_dur','hb2_freq','hb2_amp1','hb2_amp2','hb2_amp3','hb2_amp4','hb2_amp5','hb2_amp6','hb2_amp7','hb2_amp8','hb2_amp9','hb2_amp10','hb2_ampAvr',...
    'hb2_ampMax','hb2_maxTailAngle','hb2_minTailAngle','hb2_halfBendAngle','hb2_maxTailPos','hb2_minTailPos','hb2_halfBendPos','hb2_waveSpeed','hb2_angularVel','hb2_ampPosRate',...
    'hb2_auc1','hb2_auc2','hb2_auc3','hb2_auc4','hb2_auc5','hb2_auc6','hb2_auc7','hb2_auc8','hb2_auc9','hb2_auc10','hb2_aucAvr','hb2_aucMax','hb2_maxTailChange','hb2_meanTailChange',...
    'hb2_maxCurv','hb2_maxCurvRate','hb3_ud','hb3_numBeat','hb3_dur','hb3_freq','hb3_amp1','hb3_amp2','hb3_amp3','hb3_amp4','hb3_amp5','hb3_amp6','hb3_amp7','hb3_amp8','hb3_amp9','hb3_amp10',...
    'hb3_ampAvr','hb3_ampMax','hb3_maxTailAngle','hb3_minTailAngle','hb3_halfBendAngle','hb3_maxTailPos','hb3_minTailPos','hb3_halfBendPos','hb3_waveSpeed','hb3_angularVel','hb3_ampPosRate',...
    'hb3_auc1','hb3_auc2','hb3_auc3','hb3_auc4','hb3_auc5','hb3_auc6','hb3_auc7','hb3_auc8','hb3_auc9','hb3_auc10','hb3_aucAvr','hb3_aucMax','hb3_maxTailChange','hb3_meanTailChange','hb3_maxCurv','hb3_maxCurvRate',...
    'firstBeatAmplitudeDiff','boutAmplitudeDiff','meanBoutFreqCorr','maxBoutFreqCorr','minBoutFreqCorr','eyeConvAvrThisBout','eyeConv20FramesBeforeBout','eyeConv20FramesAfterBout','eyeConvDiff2'};
pre={'s1','s2','s3','s4','s5','s6','s7','s8','s9','s10'};
post = {'5','10','15','20','25','30','35','40','45','50'};
tmp = cellfun(@(x) cellfun(@(y) strjoin({x,y},'_'),post,'un',0),pre,'un',0);
tmp = cat(1,tmp{:})';
tmp = tmp(:);
str = [str tmp'];
for i=1:length(str)
    eval(['EnumeratorParams.' str{i} ' = ' num2str(i) ';']);
end
name = fieldnames(EnumeratorParams);
end

