EnumeratorBoutKinPar.numbHalfBeats,
EnumeratorBoutKinPar.boutDuration,
EnumeratorBoutKinPar.distBoutDuration,
EnumeratorBoutKinPar.maxBoutFreq,
EnumeratorBoutKinPar.minBoutFreq,
EnumeratorBoutKinPar.meanBoutFreq,
EnumeratorBoutKinPar.headMaxYaw,
EnumeratorBoutKinPar.headMeanYaw,
EnumeratorBoutKinPar.headMinYaw,

EnumeratorBoutKinPar.boutAngle,
EnumeratorBoutKinPar.distBoutAngle,
EnumeratorBoutKinPar.boutMaxAngle,
EnumeratorBoutKinPar.boutMaxAngularSpeed,
EnumeratorBoutKinPar.boutAvrAngularSpeed,

EnumeratorBoutKinPar.boutDistanceX,
EnumeratorBoutKinPar.boutDistanceY,
EnumeratorBoutKinPar.boutSpeedX,
EnumeratorBoutKinPar.boutSpeedY,
EnumeratorBoutKinPar.distBoutDistanceX,
EnumeratorBoutKinPar.distBoutDistanceY,
EnumeratorBoutKinPar.distBoutSpeedX,
EnumeratorBoutKinPar.distBoutSpeedY, 

EnumeratorBoutKinPar.maxTailChangeAvr, 
EnumeratorBoutKinPar.meanTailChangeAvr, 
EnumeratorBoutKinPar.maxTailChangeMax, 
EnumeratorBoutKinPar.meanTailChangeMax, 

EnumeratorBoutKinPar.boutTailWaveSpeedMax, 
EnumeratorBoutKinPar.boutTailWaveSpeedMin, 
EnumeratorBoutKinPar.boutTailWaveSpeedMean, 
EnumeratorBoutKinPar.boutTailAngularVelocityMax, 
EnumeratorBoutKinPar.boutTailAngularVelocityMin, 
EnumeratorBoutKinPar.boutTailAngularVelocityMean, 
EnumeratorBoutKinPar.boutTailAmplitudePositionRateMax, 
EnumeratorBoutKinPar.boutTailAmplitudePositionRateMin, 
EnumeratorBoutKinPar.boutTailAmplitudePositionRateMean, 

EnumeratorBoutKinPar.boutHalfBendingPosMax, 
EnumeratorBoutKinPar.boutHalfBendingPosMin, 
EnumeratorBoutKinPar.boutHalfBendingPosMean, 

EnumeratorBoutKinPar.boutCruvatureMax, 
EnumeratorBoutKinPar.boutCruvatureMin, 
EnumeratorBoutKinPar.boutCruvatureMean, 

EnumeratorBoutKinPar.boutCurvatureRateMax, 
EnumeratorBoutKinPar.boutCurvatureRateMin, 
EnumeratorBoutKinPar.boutCurvatureRateMean, 

EnumeratorBoutKinPar.boutAbsAmplitude1Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude2Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude3Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude4Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude5Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude6Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude7Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude8Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude9Avr, 
EnumeratorBoutKinPar.boutAbsAmplitude10Avr, 

EnumeratorBoutKinPar.boutAmplitude1Max, 
EnumeratorBoutKinPar.boutAmplitude2Max, 
EnumeratorBoutKinPar.boutAmplitude3Max, 
EnumeratorBoutKinPar.boutAmplitude4Max, 
EnumeratorBoutKinPar.boutAmplitude5Max, 
EnumeratorBoutKinPar.boutAmplitude6Max, 
EnumeratorBoutKinPar.boutAmplitude7Max, 
EnumeratorBoutKinPar.boutAmplitude8Max, 
EnumeratorBoutKinPar.boutAmplitude9Max, 
EnumeratorBoutKinPar.boutAmplitude10Max, 

EnumeratorBoutKinPar.absAUC1, 
EnumeratorBoutKinPar.absAUC2, 
EnumeratorBoutKinPar.absAUC3, 
EnumeratorBoutKinPar.absAUC4, 
EnumeratorBoutKinPar.absAUC5, 
EnumeratorBoutKinPar.absAUC6, 
EnumeratorBoutKinPar.absAUC7, 
EnumeratorBoutKinPar.absAUC8, 
EnumeratorBoutKinPar.absAUC9, 
EnumeratorBoutKinPar.absAUC10, 

EnumeratorBoutKinPar.beat1upDown, 
EnumeratorBoutKinPar.beat1numbBeatInBout, 
EnumeratorBoutKinPar.beat1beatDuration, 
EnumeratorBoutKinPar.beat1beatFrequency, 

EnumeratorBoutKinPar.beat1beatAmplitude1,
EnumeratorBoutKinPar.beat1beatAmplitude2, 
EnumeratorBoutKinPar.beat1beatAmplitude3, 
EnumeratorBoutKinPar.beat1beatAmplitude4,
EnumeratorBoutKinPar.beat1beatAmplitude5, 
EnumeratorBoutKinPar.beat1beatAmplitude6, 
EnumeratorBoutKinPar.beat1beatAmplitude7, 
EnumeratorBoutKinPar.beat1beatAmplitude8, 
EnumeratorBoutKinPar.beat1beatAmplitude9, 
EnumeratorBoutKinPar.beat1beatAmplitude10, 
EnumeratorBoutKinPar.beat1beatAmplitudeAvr, 
EnumeratorBoutKinPar.beat1beatAmplitudeMax, 
EnumeratorBoutKinPar.beat1beatMaxTailAngle, 
EnumeratorBoutKinPar.beat1beatMinTailAngle, 
EnumeratorBoutKinPar.beat1beatHalfBendAngle, 
EnumeratorBoutKinPar.beat1beatMaxTailPos, 
EnumeratorBoutKinPar.beat1beatMinTailPos, 
EnumeratorBoutKinPar.beat1beatHalfBendPos, 

EnumeratorBoutKinPar.beat1beatWaveSpeed, 
EnumeratorBoutKinPar.beat1beatAngularVelocity, 
EnumeratorBoutKinPar.beat1beatAmplitudePositionRate, 

EnumeratorBoutKinPar.beat1AUC1, 
EnumeratorBoutKinPar.beat1AUC2, 
EnumeratorBoutKinPar.beat1AUC3,  
EnumeratorBoutKinPar.beat1AUC4, 
EnumeratorBoutKinPar.beat1AUC5, 
EnumeratorBoutKinPar.beat1AUC6,
EnumeratorBoutKinPar.beat1AUC7, 
EnumeratorBoutKinPar.beat1AUC8, 
EnumeratorBoutKinPar.beat1AUC9, 
EnumeratorBoutKinPar.beat1AUC10,
EnumeratorBoutKinPar.beat1AUCAvr, 
EnumeratorBoutKinPar.beat1AUCmax, 

EnumeratorBoutKinPar.beat1beatAngle, 
EnumeratorBoutKinPar.beat1beatMaxAngle, 
EnumeratorBoutKinPar.beat1beatMaxAngularSpeed, 

EnumeratorBoutKinPar.beat1beatDistanceX, 
EnumeratorBoutKinPar.beat1beatDistanceY, 
EnumeratorBoutKinPar.beat1beatSpeedX, 
EnumeratorBoutKinPar.beat1beatSpeedY, 

EnumeratorBoutKinPar.beat1maxTailChange, 
EnumeratorBoutKinPar.beat1meanTailChange, 

EnumeratorBoutKinPar.beat1beatMaxCurvature, 
EnumeratorBoutKinPar.beat1beatMaxCurvatureRate, 

EnumeratorBoutKinPar.beat2upDown, 
EnumeratorBoutKinPar.beat2numbBeatInBout, 
EnumeratorBoutKinPar.beat2beatDuration, 
EnumeratorBoutKinPar.beat2beatFrequency, 

EnumeratorBoutKinPar.beat2beatAmplitude1, 
EnumeratorBoutKinPar.beat2beatAmplitude2, 
EnumeratorBoutKinPar.beat2beatAmplitude3, 
EnumeratorBoutKinPar.beat2beatAmplitude4, 
EnumeratorBoutKinPar.beat2beatAmplitude5, 
EnumeratorBoutKinPar.beat2beatAmplitude6, 
EnumeratorBoutKinPar.beat2beatAmplitude7, 
EnumeratorBoutKinPar.beat2beatAmplitude8, 
EnumeratorBoutKinPar.beat2beatAmplitude9, 
EnumeratorBoutKinPar.beat2beatAmplitude10, 
EnumeratorBoutKinPar.beat2beatAmplitudeAvr, 
EnumeratorBoutKinPar.beat2beatAmplitudeMax, 
EnumeratorBoutKinPar.beat2beatMaxTailAngle, 
EnumeratorBoutKinPar.beat2beatMinTailAngle, 

EnumeratorBoutKinPar.beat2beatHalfBendAngle, 
EnumeratorBoutKinPar.beat2beatMaxTailPos, 
EnumeratorBoutKinPar.beat2beatMinTailPos, 
EnumeratorBoutKinPar.beat2beatHalfBendPos, 

EnumeratorBoutKinPar.beat2beatWaveSpeed, 
EnumeratorBoutKinPar.beat2beatAngularVelocity, 
EnumeratorBoutKinPar.beat2beatAmplitudePositionRate, 

EnumeratorBoutKinPar.beat2AUC1, 
EnumeratorBoutKinPar.beat2AUC2, 
EnumeratorBoutKinPar.beat2AUC3, 
EnumeratorBoutKinPar.beat2AUC4, 
EnumeratorBoutKinPar.beat2AUC5, 
EnumeratorBoutKinPar.beat2AUC6, 
EnumeratorBoutKinPar.beat2AUC7, 
EnumeratorBoutKinPar.beat2AUC8, 
EnumeratorBoutKinPar.beat2AUC9, 
EnumeratorBoutKinPar.beat2AUC10, 
EnumeratorBoutKinPar.beat2AUCAvr,  
EnumeratorBoutKinPar.beat2AUCmax, 

EnumeratorBoutKinPar.beat2beatAngle, 
EnumeratorBoutKinPar.beat2beatMaxAngle, 
EnumeratorBoutKinPar.beat2beatMaxAngularSpeed,  

EnumeratorBoutKinPar.beat2beatDistanceX, 
EnumeratorBoutKinPar.beat2beatDistanceY, 
EnumeratorBoutKinPar.beat2beatSpeedX, 
EnumeratorBoutKinPar.beat2beatSpeedY, 
EnumeratorBoutKinPar.beat2maxTailChange, 
EnumeratorBoutKinPar.beat2meanTailChange, 

EnumeratorBoutKinPar.beat2beatMaxCurvature, 
EnumeratorBoutKinPar.beat2beatMaxCurvatureRate, 

EnumeratorBoutKinPar.beat3upDown, 
EnumeratorBoutKinPar.beat3numbBeatInBout, 
EnumeratorBoutKinPar.beat3beatDuration, 
EnumeratorBoutKinPar.beat3beatFrequency, 

EnumeratorBoutKinPar.beat3beatAmplitude1, 
EnumeratorBoutKinPar.beat3beatAmplitude2, 
EnumeratorBoutKinPar.beat3beatAmplitude3,
EnumeratorBoutKinPar.beat3beatAmplitude4, 
EnumeratorBoutKinPar.beat3beatAmplitude5, 
EnumeratorBoutKinPar.beat3beatAmplitude6, 
EnumeratorBoutKinPar.beat3beatAmplitude7, 
EnumeratorBoutKinPar.beat3beatAmplitude8, 
EnumeratorBoutKinPar.beat3beatAmplitude9, 
EnumeratorBoutKinPar.beat3beatAmplitude10, 
EnumeratorBoutKinPar.beat3beatAmplitudeAvr, 
EnumeratorBoutKinPar.beat3beatAmplitudeMax, 

EnumeratorBoutKinPar.beat3beatMaxTailAngle, 
EnumeratorBoutKinPar.beat3beatMinTailAngle, 
EnumeratorBoutKinPar.beat3beatHalfBendAngle, 
EnumeratorBoutKinPar.beat3beatMaxTailPos, 
EnumeratorBoutKinPar.beat3beatMinTailPos, 
EnumeratorBoutKinPar.beat3beatHalfBendPos, 

EnumeratorBoutKinPar.beat3beatWaveSpeed, 
EnumeratorBoutKinPar.beat3beatAngularVelocity,
EnumeratorBoutKinPar.beat3beatAmplitudePositionRate, 

EnumeratorBoutKinPar.beat3AUC1, 
EnumeratorBoutKinPar.beat3AUC2, 
EnumeratorBoutKinPar.beat3AUC3, 
EnumeratorBoutKinPar.beat3AUC4, 
EnumeratorBoutKinPar.beat3AUC5, 
EnumeratorBoutKinPar.beat3AUC6, 
EnumeratorBoutKinPar.beat3AUC7, 
EnumeratorBoutKinPar.beat3AUC8, 
EnumeratorBoutKinPar.beat3AUC9, 
EnumeratorBoutKinPar.beat3AUC10, 
EnumeratorBoutKinPar.beat3AUCAvr, 
EnumeratorBoutKinPar.beat3AUCmax, 

EnumeratorBoutKinPar.beat3beatAngle, 
EnumeratorBoutKinPar.beat3beatMaxAngle, 
EnumeratorBoutKinPar.beat3beatMaxAngularSpeed, 

EnumeratorBoutKinPar.beat3beatDistanceX, 
EnumeratorBoutKinPar.beat3beatDistanceY, 
EnumeratorBoutKinPar.beat3beatSpeedX, 
EnumeratorBoutKinPar.beat3beatSpeedY, 
EnumeratorBoutKinPar.beat3maxTailChange, 
EnumeratorBoutKinPar.beat3meanTailChange, 

EnumeratorBoutKinPar.beat3beatMaxCurvature, 
EnumeratorBoutKinPar.beat3beatMaxCurvatureRate, 

EnumeratorBoutKinPar.firstBeatAmplitudeDiff, 
EnumeratorBoutKinPar.boutAmplitudeDiff, 

EnumeratorBoutKinPar.meanBoutFreqCorr, 
EnumeratorBoutKinPar.maxBoutFreqCorr, 
EnumeratorBoutKinPar.minBoutFreqCorr, 


EnumeratorBoutKinPar.maxDiffBodyAngle, 

EnumeratorBoutKinPar.boutMaxAngleRatio, 

EnumeratorBoutKinPar.C1Angle, 
EnumeratorBoutKinPar.C1Duration, 
EnumeratorBoutKinPar.C1MaxAngularSpeed, 

EnumeratorBoutKinPar.C2Angle, 
EnumeratorBoutKinPar.C2Duration, 
EnumeratorBoutKinPar.C2MaxAngularSpeed, 

EnumeratorBoutKinPar.eyeConvAvr,